//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Department
{
    public Department()
    {
        this.Doctors = new HashSet<Doctor>();
    }

    public int DepartmentId { get; set; }
    public string DepartmentName { get; set; }

    public virtual ICollection<Doctor> Doctors { get; set; }
}

public partial class Doctor
{
    public int DoctorID { get; set; }
    public string dName { get; set; }
    public string dEmail { get; set; }
    public string dScheduleDay { get; set; }
    public int DepartmentId { get; set; }
    public int RoomId { get; set; }

    public virtual Department Department { get; set; }
    public virtual Room Room { get; set; }
}

public partial class Room
{
    public Room()
    {
        this.Doctors = new HashSet<Doctor>();
    }

    public int RoomId { get; set; }
    public string RoomNo { get; set; }

    public virtual ICollection<Doctor> Doctors { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}
